### ISSUE TITLE
login not working !

### ISSUE THREAD

**Issue by AminAzGol** [milanifard/Ontirandoc#11]
**Describe the bug**
at commit 276a43f157c4b48c91261db5d5d87d66465bb41f
User omid & omid3000 login fails. I checked the database and there's no such user in user table.
there's might be some code that removes the user at first run.

**Comment by mghayour** [comment]
I fixed it.

Someone had a mistake in  manage_AccountSpecs test cases
He removed omid/omid3000 acount

If (omid, omid3000) dosent work for you

Add omid record to your DB, or restore DB backup
Table: projectmanagement/accountspecs
```sql
INSERT INTO AccountSpecs VALUES (1,'omid','30f9dd65de612bfe458a871b90eabb3026c9fb29',1,'omid')
```
